/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package me.yokeyword.fragmentation_swipeback;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static int shadow_bottom=0x7f020000;
        public static int shadow_left=0x7f020001;
        public static int shadow_right=0x7f020002;
    }
}
